import {useEffect,useRef} from 'react';
import type {Filters,Meta} from './shared/types';
import {datePreset} from './shared/filters';

export default function FiltersDialog({open,close,filters,setFilters,meta,apply,reset}:{open:boolean;close:()=>void;filters:Filters;setFilters:(f:Filters)=>void;meta:Meta|null;apply:()=>void;reset:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();if(!open&&dialog.current?.open)dialog.current?.close()},[open]);
 function patch(v:Partial<Filters>){setFilters({...filters,...v})}
 return <dialog ref={dialog} className="filter-dialog" aria-labelledby="filter-heading" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}}>
  <form className="filter-form" onSubmit={e=>{e.preventDefault();apply();close()}}>
   <div className="dialog-heading"><div><p className="eyebrow">ПОД ВАШИ ПЛАНЫ</p><h2 id="filter-heading">Фильтры</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Закрыть фильтры">×</button></div>
   <p className="muted filter-intro">Условия из поисковой строки появляются здесь. Их можно изменить.</p>
   <section><h3>Где</h3><label>Город<select aria-label="Город" value={filters.city} onChange={e=>patch({city:e.target.value})}>{meta?.cities.map(c=><option value={c.slug} key={c.id}>{c.label}</option>)}</select></label><label className="check nearby-toggle"><input type="checkbox" checked={filters.include_nearby} onChange={e=>patch({include_nearby:e.target.checked})}/>Также ближайшие города и посёлки</label></section>
   <section><h3>Когда</h3><div className="chips">{[['Сегодня','today'],['Завтра','tomorrow'],['Выходные','weekend'],['Неделя','week']].map(([label,key])=><button type="button" key={key} onClick={()=>patch(datePreset(key))}>{label}</button>)}<button type="button" onClick={()=>patch({date_from:'',date_to:''})}>Любая дата</button></div><div className="form-pair"><label>С даты<input type="date" value={filters.date_from} onChange={e=>patch({date_from:e.target.value})}/></label><label>По дату<input type="date" min={filters.date_from} value={filters.date_to} onChange={e=>patch({date_to:e.target.value})}/></label></div><label>Время<select value={filters.time_of_day} onChange={e=>patch({time_of_day:e.target.value})}><option value="">В любое время</option><option value="morning">Утром</option><option value="afternoon">Днём</option><option value="evening">Вечером</option><option value="night">Ночью</option></select></label></section>
   <section><h3>Компания и бюджет</h3><div className="form-pair"><label>Количество человек<input type="number" min="1" max="100" value={filters.party_size} onChange={e=>patch({party_size:e.target.value})}/></label><label>На всю компанию до, ₽<input type="number" min="0" value={filters.budget_total} placeholder="Любой бюджет" onChange={e=>patch({budget_total:e.target.value})}/></label></div><label>На человека до, ₽<input type="number" min="0" value={filters.price_max} placeholder="Без ограничения" onChange={e=>patch({price_max:e.target.value})}/></label><label className="check nearby-toggle"><input type="checkbox" checked={filters.is_free} onChange={e=>patch({is_free:e.target.checked})}/>Только бесплатно</label></section>
   <section><h3>Что интересно</h3><div className="chips filter-category-chips">{meta?.categories.filter(c=>!['other','stock','yarmarki-razvlecheniya-yarmarki','social-activity','shopping'].includes(c.slug)).map(c=><button type="button" key={c.id} aria-pressed={filters.categories.includes(c.slug)} onClick={()=>patch({categories:filters.categories.includes(c.slug)?filters.categories.filter(x=>x!==c.slug):[...filters.categories,c.slug]})}>{c.label}</button>)}</div></section>
   <section><h3>Ещё немного точнее</h3><div className="form-pair"><label>Маркировка события<select value={filters.age_exact} onChange={e=>patch({age_exact:e.target.value})}><option value="">Любая</option>{[0,6,12,16,18].map(x=><option value={x} key={x}>Только {x}+</option>)}</select></label><label>Порядок<select value={filters.sort} onChange={e=>patch({sort:e.target.value})}><option value="date">Ближайшие сначала</option><option value="price">Сначала недорогие</option></select></label></div><label>Название или исполнитель<input value={filters.query} onChange={e=>patch({query:e.target.value})} placeholder="Например, Баста"/></label><label>Что показывать<select value={filters.kind} onChange={e=>patch({kind:e.target.value})}><option value="">События и места</option><option value="event">События с датами</option><option value="place">Места для посещения</option></select></label><details className="format-details"><summary>Жанры и форматы</summary><div className="genre-groups">{meta?.interests.map(i=><div key={i.id}><p>{i.label}</p><div className="chips">{i.categories.map(c=><button type="button" key={c.id} aria-pressed={filters.interest_categories.includes(c.slug)} onClick={()=>patch({interest_categories:filters.interest_categories.includes(c.slug)?filters.interest_categories.filter(x=>x!==c.slug):[...filters.interest_categories,c.slug]})}>{c.label}</button>)}</div></div>)}</div></details></section>
   <div className="dialog-actions"><button type="button" onClick={reset}>Сбросить</button><button className="primary" type="submit">Показать события</button></div>
  </form>
 </dialog>;
}
