import {useEffect,useRef,useState} from 'react';
import type {Meta,Preferences} from './shared/types';
import {api,body} from './shared/api';
import {Notice} from './components';
const empty:Preferences={home_city:null,include_nearby:true,age_group_id:null,interest_ids:[],interest_category_ids:[],organizer_ids:[],budget_min:null,budget_max:null};
const symbols:Record<string,string>={music:'♫',theatre:'◒',cinema:'▷',art:'▧',humor:'☺',education:'✦',leisure:'↗',games:'⚄',active:'⌁',family:'♡',nightlife:'☾'};
const captions:Record<string,string>={music:'От камерного джаза до больших концертов',theatre:'Классика, драма и новые формы',cinema:'Большой экран и камерные показы',art:'Коллекции, выставки и новые имена',humor:'Поводы посмеяться',education:'Встречи, практики и открытия',leisure:'Парки, архитектура и городские маршруты',games:'Антикафе, настолки и приключения',active:'Движение и новые ощущения',family:'Впечатления для всей семьи',nightlife:'Танцы, музыка и встречи'};
export default function Profile({meta,saved}:{meta:Meta|null;saved:(p:Preferences)=>void}){
 const [form,setForm]=useState<Preferences>(empty),[active,setActive]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);api<Preferences>('/me/preferences').then(v=>{if(alive){setForm({...empty,...v,include_nearby:v.home_city?v.include_nearby:true});setLoaded(true)}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[reload]);
 function topic(id:string,parent:string){setForm(v=>{const selected=v.interest_category_ids.includes(id);return {...v,interest_ids:v.interest_ids.includes(parent)?v.interest_ids:[...v.interest_ids,parent],interest_category_ids:selected?v.interest_category_ids.filter(x=>x!==id):[...v.interest_category_ids,id]}})}
 function direction(id:string){setForm(v=>{const children=meta?.interests.find(x=>x.id===id)?.categories.map(x=>x.id)||[];const all=v.interest_ids.includes(id)&&!v.interest_category_ids.some(x=>children.includes(x));return {...v,interest_ids:all?v.interest_ids.filter(x=>x!==id):[...new Set([...v.interest_ids,id])],interest_category_ids:v.interest_category_ids.filter(x=>!children.includes(x))}})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<Preferences>('/me/preferences',{method:'PUT',body:body({...form,organizer_ids:[]})});saved(result)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const topics=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(active&&!topics.current?.open)topics.current?.showModal();if(!active&&topics.current?.open)topics.current?.close()},[active]);
 const group=meta?.interests.find(x=>x.id===active);
 return <section className="profile-page"><p className="eyebrow">ВАШ ГОРОД. ВАШ РИТМ.</p><h1>То, что интересно именно вам.</h1><p className="muted">Отметьте любимые занятия. Менять планы и интересы можно в любой момент.</p>
 {error&&<Notice>{error}{!loaded&&<button onClick={()=>setReload(x=>x+1)}>Повторить</button>}</Notice>}
 {loading?<p>Загружаем профиль…</p>:<form onSubmit={save}>
  <section className="profile-basics"><div className="form-pair"><label>Где вы живёте?<select required value={form.home_city||''} onChange={e=>setForm({...form,home_city:e.target.value})}><option value="">Выберите город или посёлок</option>{['msk','krd'].map(area=><optgroup label={area==='msk'?'Москва и Подмосковье':'Краснодар и окрестности'} key={area}>{meta?.cities.filter(c=>c.area===area).map(c=><option key={c.id} value={c.slug}>{c.label}</option>)}</optgroup>)}</select></label><label>Возрастная группа<select required value={form.age_group_id||''} onChange={e=>setForm({...form,age_group_id:e.target.value})}><option value="">Выберите</option>{meta?.age_groups.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label></div>
   <label className="check nearby-toggle"><input type="checkbox" checked={form.include_nearby} onChange={e=>setForm({...form,include_nearby:e.target.checked})}/>Показывать также ближайшие города и посёлки</label>
   <p className="form-hint">Сейчас афиша охватывает Москву, Краснодар и перечисленные окрестности. Город можно сменить в поиске.</p>
  </section>
  <div className="section-title"><h2>За чем хочется выйти из дома?</h2></div>
  <div className="interest-grid">{meta?.interests.map(i=>{const chosen=form.interest_ids.includes(i.id),count=i.categories.filter(c=>form.interest_category_ids.includes(c.id)).length;return <button type="button" className="interest-card" key={i.id} aria-expanded={active===i.id} aria-controls="interest-topics" onClick={()=>setActive(active===i.id?null:i.id)} data-selected={chosen}><span className="interest-symbol" aria-hidden="true">{symbols[i.slug]||'✧'}</span><strong>{i.label}</strong><small>{captions[i.slug]||'Найдите что-нибудь своё'}</small><span className="interest-state">{chosen?(count?`${count} выбрано`:'Выбрано'):'Выбрать ↗'}</span></button>})}</div>
  <dialog ref={topics} className="interest-dialog" id="interest-topics" aria-labelledby="topics-heading" onCancel={e=>{e.preventDefault();setActive(null)}} onClick={e=>{if(e.target===e.currentTarget)setActive(null)}}>{group&&<section className="interest-topics"><div className="topics-heading"><h3 id="topics-heading">{group.label}</h3><button type="button" className="icon-button" aria-label="Свернуть темы" onClick={()=>setActive(null)}>×</button></div><div className="chips"><button type="button" className="all-interest" aria-pressed={form.interest_ids.includes(group.id)&&!group.categories.some(c=>form.interest_category_ids.includes(c.id))} onClick={()=>direction(group.id)}>Всё направление</button>{group.categories.map(c=><button type="button" key={c.id} aria-pressed={form.interest_category_ids.includes(c.id)} onClick={()=>topic(c.id,group.id)}>{c.label}</button>)}</div><button className="primary topics-done" type="button" onClick={()=>setActive(null)}>Готово</button></section>}</dialog>
  <details className="profile-budget"><summary>Предпочитаемый бюджет <span>необязательно</span></summary><div className="form-pair"><label>От, ₽ на человека<input type="number" min="0" value={form.budget_min??''} onChange={e=>setForm({...form,budget_min:e.target.value===''?null:Number(e.target.value)})}/></label><label>До, ₽ на человека<input type="number" min={form.budget_min??0} value={form.budget_max??''} onChange={e=>setForm({...form,budget_max:e.target.value===''?null:Number(e.target.value)})}/></label></div></details>
  <div className="profile-save"><p>Всё готово к новым впечатлениям.</p><button className="primary" disabled={busy||!meta||!loaded}>{busy?'Сохраняем…':'Сохранить и перейти к афише'}</button></div>
 </form>}</section>;
}
