"""normalized schema from Anya 2026-09-27

Revision ID: 3887022d9d15
Revises: 
Create Date: 2026-09-27 10:52:41.578906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3887022d9d15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_groups',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cities',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('event_sources',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interests',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('organizers',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_url')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('max_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('max_user_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('interest_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('group_choices',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('creator_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('city_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['event_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_categories',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('interest_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('moderation_logs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('user_interests',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('interest_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_table('user_organizers',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('organizer_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organizer_id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('age_group_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.CheckConstraint('budget_max IS NULL OR budget_max >= 0'),
    sa.CheckConstraint('budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max'),
    sa.CheckConstraint('budget_min IS NULL OR budget_min >= 0'),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('age_limit IS NULL OR (age_limit >= 0 AND age_limit <= 100)'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['event_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category_id'), ['category_id'], unique=False)

    op.create_table('user_interest_categories',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interest_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('event_chats',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('max_chat_id', sa.String(length=64), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('max_chat_id')
    )
    op.create_table('event_interest_categories',
    sa.Column('event_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interest_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'category_id')
    )
    op.create_table('event_occurrences',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('city_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('price_text', sa.Text(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_available', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','CANCELLED','POSTPONED','FINISHED')"),
    sa.CheckConstraint('ends_at IS NULL OR ends_at >= starts_at'),
    sa.CheckConstraint('price_max IS NULL OR price_max >= 0'),
    sa.CheckConstraint('price_min IS NULL OR price_max IS NULL OR price_min <= price_max'),
    sa.CheckConstraint('price_min IS NULL OR price_min >= 0'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'city_id', 'starts_at')
    )
    with op.batch_alter_table('event_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_occurrences_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_occurrences_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_occurrences_price_min'), ['price_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_occurrences_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index('ix_occurrence_city_time', ['city_id', 'starts_at'], unique=False)

    op.create_table('event_organizers',
    sa.Column('event_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('organizer_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'organizer_id')
    )
    op.create_table('event_reports',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'occurrence_id')
    )
    op.create_table('group_choice_events',
    sa.Column('choice_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('recommendation_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['group_choices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('choice_id', 'occurrence_id')
    )
    op.create_table('tracked_events',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('active','cancelled')"),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'occurrence_id')
    )
    op.create_table('group_choice_votes',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('choice_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['choice_id', 'occurrence_id'], ['group_choice_events.choice_id', 'group_choice_events.occurrence_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['choice_id'], ['group_choices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('choice_id', 'user_id')
    )
    op.create_table('notification_jobs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tracking_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracking_id'], ['tracked_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('notification_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_jobs_scheduled_at'))

    op.drop_table('notification_jobs')
    op.drop_table('group_choice_votes')
    op.drop_table('tracked_events')
    op.drop_table('group_choice_events')
    op.drop_table('event_reports')
    op.drop_table('event_organizers')
    with op.batch_alter_table('event_occurrences', schema=None) as batch_op:
        batch_op.drop_index('ix_occurrence_city_time')
        batch_op.drop_index(batch_op.f('ix_event_occurrences_starts_at'))
        batch_op.drop_index(batch_op.f('ix_event_occurrences_price_min'))
        batch_op.drop_index(batch_op.f('ix_event_occurrences_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_occurrences_city_id'))

    op.drop_table('event_occurrences')
    op.drop_table('event_interest_categories')
    op.drop_table('event_chats')
    op.drop_table('user_interest_categories')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_category_id'))

    op.drop_table('events')
    op.drop_table('user_preferences')
    op.drop_table('user_organizers')
    op.drop_table('user_interests')
    op.drop_table('moderation_logs')
    op.drop_table('interest_categories')
    op.drop_table('import_runs')
    op.drop_table('group_choices')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('organizers')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_at'))

    op.drop_table('jobs')
    op.drop_table('interests')
    op.drop_table('event_sources')
    op.drop_table('cities')
    op.drop_table('age_groups')
    # ### end Alembic commands ###
